---
- name: use wait for connection
  hosts: all
  remote_user: ec2-user
  gather_facts: false

  tasks:
# This task will wait to get a ssh connetion to the provisioned aws hosts
    - name: wait to connect
      wait_for_connection:
