---
- name: CLOUD MANAGER PLAYBOOK EXAMPLES
  connection: local
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Config Rule for AWS Config
      aws_config_rule:
        name: config-bucket-sean-jun9-2019
        region: us-east-2
        state: present
        description: 'This AWS Config rule checks for public write access on S3 buckets'
        scope:
            compliance_types:
                - 'AWS::S3::Bucket'
        source:
            owner: AWS
            identifier: 'S3_BUCKET_PUBLIC_WRITE_PROHIBITED'
