---
- name: grab linux facts
  hosts: all
  gather_facts: yes

- name: build developer report
  hosts: node1
  gather_facts: False

  vars:
    file_path: /var/www/html/report/index.html

  tasks:

    - name: create HTML report
      become: yes
      template:
        src: report.j2
        dest: "{{ file_path }}"

    - name: DISPLAY LINK TO INVENTORY REPORT
      debug:
        msg: "Please go to http://{{ansible_host}}/report"
