---
- name: doing automation
  debug:
    msg: "i am going to run the httpd role"

- name: install apache
  yum:
    name: httpd
    state: present

- name: start httpd
  service:
    name: httpd
    state: started

- name: copy index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html
